# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sql_write_pb2 as sql__write__pb2


class SQLWriteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteUsers = channel.unary_unary(
                '/sql_write.SQLWrite/WriteUsers',
                request_serializer=sql__write__pb2.Users.SerializeToString,
                response_deserializer=sql__write__pb2.Ack.FromString,
                )


class SQLWriteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WriteUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SQLWriteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteUsers,
                    request_deserializer=sql__write__pb2.Users.FromString,
                    response_serializer=sql__write__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sql_write.SQLWrite', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SQLWrite(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WriteUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sql_write.SQLWrite/WriteUsers',
            sql__write__pb2.Users.SerializeToString,
            sql__write__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
